### ISSUE TITLE
/redfish/v1/TelemetryService/Oem/Dell/D4D/Reports

### ISSUE THREAD

**Issue by windsparks33** [DMTF/Redfish-Interop-Validator#166]
Config setup:
Enterprise License
iDRAC System
4000 Present D4D reports  each report returns a 403 (forbidden needs upgraded license)

Expectation, the script should run to completion.  Error is that the script hangs.

**Comment by mraineri** [comment]
To clarify things a bit, the tool's current behavior is to report errors on resources that cannot be obtained. The interop validator does an exhaustive scan of the service, even if it doesn't need to.

I would like to propose we allow for the tool to consider this a warning condition, since the service can still meet the profile's requirements without providing access to everything in the model.

**Comment by jyundt** [comment]
@mraineri one other thing to note about this issue: these D4D endpoints are still scanned even when using the `--nooemcheck` flag. What is expected behavior when using `--nooemcheck`, should these just be skipped? Or would they still be scanned but not included in the final report?

**Comment by jyundt** [comment]
Ah got it. In that case, would you like me to open a separate GH issue for that? Or just hijack this issue?

**Comment by mraineri** [comment]
Let's open a different one; that might be tougher to solve since I know there's a similar issue in the service validator that's been outstanding (and doesn't seem to have an easy solution).

**Comment by jyundt** [comment]
> Let's open a different one; that might be tougher to solve since I know there's a similar issue in the service validator that's been outstanding (and doesn't seem to have an easy solution).

Sounds good, I just opened #167 for this.

**Comment by mraineri** [comment]
1/13: From today's call, folks agree that we can tag this as a "warning" and move on since you can still meet the profile's requirements while not stepping into every URI.
